name: project_management_webview
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.11.0
  path_provider: ^2.0.11
  permission_handler: ^11.3.0
  http: ^1.3.0
  android_intent_plus: ^4.0.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

